services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: docker
      DB_USERNAME: root
      DB_PASSWORD: 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  db_data: